package com.rank.interactive.app;

import java.math.BigDecimal;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.context.event.EventListener;
import org.springframework.stereotype.Component;

import com.rank.interactive.app.model.Player;
import com.rank.interactive.app.model.Transaction;
import com.rank.interactive.app.repo.PlayerRepository;
import com.rank.interactive.app.repo.TransactionRepository;

@Component
public class DemoData {

	@Autowired
	PlayerRepository playerRepo;
	
	@Autowired
	TransactionRepository transactionRepo;
	
	@EventListener
	public void appReady(ApplicationReadyEvent event) throws Exception {
		
		//Load Demo Player data
		Player player1 = new Player();
		Player player2 = new Player();
		
		//IDs are auto generated by JPA
		player1.setName("Player 1");
		player1.setUsername("Player1@rank.com");
		
		player2.setName("Player 2");
		player2.setUsername("Player2@rank.com");
		
		playerRepo.save(player1);
		playerRepo.save(player2);
		
		//Load Transaction for Players
		Transaction tranx1 = new Transaction();
		Transaction tranx2 = new Transaction();
		
		tranx1.setBalance(new BigDecimal("2000.00"));
		tranx1.setPlayer(player1);
		
		tranx2.setBalance(new BigDecimal("4000.00"));
		tranx2.setPlayer(player2);
		
		transactionRepo.save(tranx1);
		transactionRepo.save(tranx2);


	}
}
